I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 287, in script
    python:
ScriptError: could not find label 'start'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/aaron/Documents/coding/renpy-8.0.3-sdk/renpy/bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "/home/aaron/Documents/coding/renpy-8.0.3-sdk/renpy/main.py", line 660, in main
    run(restart)
  File "/home/aaron/Documents/coding/renpy-8.0.3-sdk/renpy/main.py", line 146, in run
    renpy.execution.run_context(True)
  File "/home/aaron/Documents/coding/renpy-8.0.3-sdk/renpy/execution.py", line 938, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 287, in script
    python:
  File "/home/aaron/Documents/coding/renpy-8.0.3-sdk/renpy/script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'start'.

Linux-5.15.0-58-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.0.3.22090809
 
Mon Jan 30 09:18:02 2023
